// Siembra Form Sheet
// Related: T057, T063, US2, FR-011, FR-012
// Form for creating/editing siembras with validation

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import '../models/siembra.dart';
import '../models/estanque.dart';
import '../services/siembras_service.dart';
import '../services/estanques_service.dart';
import '../widgets/bottom_sheet_form.dart';

class SiembraFormSheet extends StatefulWidget {
  final Siembra? siembra; // null for create, not null for edit
  final int? preselectedEstanqueId; // For creating from estanque detail
  final VoidCallback? onSaved;

  const SiembraFormSheet({
    super.key,
    this.siembra,
    this.preselectedEstanqueId,
    this.onSaved,
  });

  @override
  State<SiembraFormSheet> createState() => _SiembraFormSheetState();

  /// Show siembra form as bottom sheet
  static Future<bool?> show(
    BuildContext context, {
    Siembra? siembra,
    int? preselectedEstanqueId,
    VoidCallback? onSaved,
  }) {
    return showModalBottomSheet<bool>(
      context: context,
      isScrollControlled: true,
      isDismissible: true,
      enableDrag: true,
      backgroundColor: Colors.transparent,
      builder: (context) => SiembraFormSheet(
        siembra: siembra,
        preselectedEstanqueId: preselectedEstanqueId,
        onSaved: onSaved,
      ),
    );
  }
}

class _SiembraFormSheetState extends State<SiembraFormSheet> {
  final _formKey = GlobalKey<FormState>();
  final _siembrasService = SiembrasService();
  final _estanquesService = EstanquesService();

  late TextEditingController _especieController;
  late TextEditingController _cantidadInicialController;
  late DateTime _selectedDate;
  int? _selectedEstanqueId;
  List<Estanque> _estanques = [];
  bool _isLoading = false;
  bool _isLoadingEstanques = true;

  bool get _isEditing => widget.siembra != null;

  @override
  void initState() {
    super.initState();
    _especieController = TextEditingController(
      text: widget.siembra?.especie ?? '',
    );
    _cantidadInicialController = TextEditingController(
      text: widget.siembra?.cantidadInicial.toString() ?? '',
    );
    _selectedDate = widget.siembra?.fechaSiembra ?? DateTime.now();
    _selectedEstanqueId =
        widget.siembra?.idEstanque ?? widget.preselectedEstanqueId;
    _loadEstanques();
  }

  @override
  void dispose() {
    _especieController.dispose();
    _cantidadInicialController.dispose();
    super.dispose();
  }

  Future<void> _loadEstanques() async {
    try {
      final estanques = await _estanquesService.getAll();

      if (!mounted) return;

      setState(() {
        _estanques = estanques;
        _isLoadingEstanques = false;

        // Validate preselected estanque still exists
        if (_selectedEstanqueId != null) {
          final exists = estanques.any((e) => e.id == _selectedEstanqueId);
          if (!exists) {
            _selectedEstanqueId = null;
          }
        }
      });
    } catch (e) {
      if (!mounted) return;

      setState(() => _isLoadingEstanques = false);

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error al cargar estanques: $e'),
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  Future<void> _selectDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime(2000),
      lastDate: DateTime.now().add(const Duration(days: 365)),
      locale: const Locale('es', 'ES'),
    );

    if (picked != null && picked != _selectedDate) {
      setState(() => _selectedDate = picked);
    }
  }

  Future<void> _handleSave() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    if (_selectedEstanqueId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Seleccione un estanque'),
          backgroundColor: const Color(0xFF003D7A),
        ),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final cantidadInicial = int.parse(_cantidadInicialController.text);

      if (_isEditing) {
        // Update existing siembra
        final updated = widget.siembra!.copyWith(
          especie: _especieController.text,
          fechaSiembra: _selectedDate,
          cantidadInicial: cantidadInicial,
        );
        await _siembrasService.update(updated);
      } else {
        // Create new siembra
        final newSiembra = Siembra(
          id: '', // Will be generated by database
          userId: '', // Will be auto-added by service
          idEstanque: _selectedEstanqueId!,
          especie: _especieController.text,
          fechaSiembra: _selectedDate,
          cantidadInicial: cantidadInicial,
          cantidadMuertes: 0, // Start at 0
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );
        await _siembrasService.create(newSiembra);
      }

      if (!mounted) return;

      // Close sheet and notify success
      Navigator.pop(context, true);

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            _isEditing
                ? 'Siembra actualizada exitosamente'
                : 'Siembra creada exitosamente',
          ),
          backgroundColor: const Color(0xFF00BCD4),
        ),
      );

      // Call callback if provided
      widget.onSaved?.call();
    } catch (e) {
      if (!mounted) return;

      setState(() => _isLoading = false);

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error: ${e.toString()}'),
          backgroundColor: Colors.red,
          duration: const Duration(seconds: 4),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return BottomSheetForm(
      title: _isEditing ? 'Editar Siembra' : 'Nueva Siembra',
      formKey: _formKey,
      isLoading: _isLoading,
      onSave: _handleSave,
      children: [
        // Especie field
        TextFormField(
          controller: _especieController,
          decoration: const InputDecoration(
            labelText: 'Especie *',
            hintText: 'Ej: Tilapia',
            prefixIcon: Padding(
              padding: EdgeInsets.all(12.0),
              child: Text(
                '🐟',
                style: TextStyle(fontSize: 20),
              ),
            ),
            border: OutlineInputBorder(),
          ),
          textCapitalization: TextCapitalization.words,
          validator: (value) {
            if (value == null || value.trim().isEmpty) {
              return 'La especie es requerida';
            }
            return null;
          },
          enabled: !_isLoading,
        ),
        const SizedBox(height: 16),

        // Estanque dropdown
        if (_isLoadingEstanques)
          const Center(child: CircularProgressIndicator())
        else if (_estanques.isEmpty)
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: const Color(0xFF003D7A).withOpacity(0.1),
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: const Color(0xFF003D7A).withOpacity(0.3)),
            ),
            child: const Text(
              'No hay estanques disponibles. Cree un estanque primero.',
              style: TextStyle(color: const Color(0xFF003D7A)),
            ),
          )
        else
          DropdownButtonFormField<int>(
            value: _selectedEstanqueId,
            decoration: const InputDecoration(
              labelText: 'Estanque *',
              prefixIcon: Icon(Icons.water),
              border: OutlineInputBorder(),
            ),
            items: _estanques
                .map(
                  (estanque) => DropdownMenuItem(
                    value: estanque.id,
                    child: Text('Estanque ${estanque.numero}'),
                  ),
                )
                .toList(),
            onChanged: _isLoading
                ? null
                : (value) {
                    setState(() => _selectedEstanqueId = value);
                  },
            validator: (value) {
              if (value == null) {
                return 'Seleccione un estanque';
              }
              return null;
            },
          ),
        const SizedBox(height: 16),

        // Fecha field
        InkWell(
          onTap: _isLoading ? null : _selectDate,
          child: InputDecorator(
            decoration: const InputDecoration(
              labelText: 'Fecha de Siembra *',
              prefixIcon: Icon(Icons.calendar_today),
              border: OutlineInputBorder(),
            ),
            child: Text(
              DateFormat('dd/MM/yyyy').format(_selectedDate),
              style: const TextStyle(fontSize: 16),
            ),
          ),
        ),
        const SizedBox(height: 16),

        // Cantidad inicial field
        TextFormField(
          controller: _cantidadInicialController,
          decoration: const InputDecoration(
            labelText: 'Cantidad Inicial *',
            hintText: 'Ej: 5000',
            prefixIcon: Icon(Icons.format_list_numbered),
            border: OutlineInputBorder(),
          ),
          keyboardType: TextInputType.number,
          inputFormatters: [FilteringTextInputFormatter.digitsOnly],
          validator: (value) {
            if (value == null || value.isEmpty) {
              return 'La cantidad inicial es requerida';
            }
            final cantidad = int.tryParse(value);
            if (cantidad == null || cantidad <= 0) {
              return 'Ingrese una cantidad válida mayor a 0';
            }
            return null;
          },
          enabled: !_isLoading,
        ),
        const SizedBox(height: 8),

        // Help text
        Text(
          '* Campos requeridos',
          style: TextStyle(
            fontSize: 12,
            color: Colors.grey[600],
            fontStyle: FontStyle.italic,
          ),
        ),
      ],
    );
  }
}
